const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { replay, stable } = require("../runtime/canonical-kernel.js");
const { resolveAction, resolveActions, materializeExecutionEvents } = require("../runtime/action-executor.js");

const root = path.resolve(__dirname, "..");
const pack = JSON.parse(fs.readFileSync(path.join(root, "canon/reference-convergence/manifest.json"), "utf8"));
const events = JSON.parse(fs.readFileSync(path.join(root, "examples/reference-simulation/events.json"), "utf8"));
const base = replay(events, pack);
const beforeUnlock = replay(events.slice(0, 9), pack);
const proposal = { id: "proposal-extinguish", agent_id: "agent-a", goal_id: "mitigate-fire", at: 9, priority: 0, intent: "extinguish-fire", decision_context: { projection_identity: base.projection.identity } };
const proposalEvent = { id: "e12", session_id: "reference-session", sequence: 12, type: "agency.action.proposed", version: "v1", at: 10, phase: "action", priority: 0, domain: "agency", world: { id: pack.id, version: pack.version }, payload: proposal, causal_parents: ["e11"] };
const successful = resolveAction(base.projection, proposal, pack);
const materialized = materializeExecutionEvents(successful, proposalEvent, 13);
const completed = replay([...events, proposalEvent, ...materialized], pack);
const blocked = resolveAction(beforeUnlock.projection, { ...proposal, id: "proposal-door", intent: "open-door" }, pack);
const invalid = resolveAction(base.projection, { ...proposal, id: "proposal-invalid", intent: "invent-outcome" }, pack);
const conflicts = resolveActions(base.projection, [{ ...proposal, id: "proposal-door-a", intent: "open-door", priority: 1 }, { ...proposal, id: "proposal-door-b", intent: "open-door", priority: 2 }], pack);
const reordered = replay([...materialized, proposalEvent, ...[...events].reverse()], pack);
const checkpoint = replay(events.slice(0, 6), pack);
const fromCheckpoint = replay([...events, proposalEvent, ...materialized], pack, { state: checkpoint.state });

assert.equal(successful.status, "SUCCESS");
assert.equal(successful.generated_effects.length, 2, "successful world rule emits environmental and evidence effects");
assert.equal(blocked.status, "BLOCKED");
assert.equal(blocked.reason, "door_locked");
assert.equal(blocked.generated_effects[0].type, "evidence.trace.created", "blocked execution can create durable evidence");
assert.equal(invalid.status, "INVALID");
assert.deepEqual(conflicts.map((result) => result.status), ["SUCCESS", "BLOCKED"], "conflicting proposals resolve by canonical proposal order");
assert.equal(conflicts[1].reason, "conflict:door-a-b");
assert.equal(materialized[0].type, "agency.execution.resolved");
assert.equal(materialized[1].causal_parents[0], materialized[0].id, "effects are causally grounded in execution");
assert.equal(completed.projection.objective.environment.hazards["fire-b"].active, false, "replay applies generated environmental events");
assert.equal(completed.projection.objective.evidence.at(-1).claim, "fire-b was extinguished", "replay applies generated evidence events");
assert.deepEqual(completed.projection, reordered.projection, "materialized execution events are insertion-order independent");
assert.deepEqual(completed.projection, fromCheckpoint.projection, "execution replay preserves checkpoint equivalence");
assert.equal(stable(materialized), stable(materializeExecutionEvents(resolveAction(base.projection, proposal, pack), proposalEvent, 13)), "same inputs produce identical canonical events");
console.log("validated deterministic action execution and canonical effect resolution");
