const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { replayAgency } = require("../runtime/reference/agency.js");
const plan = JSON.parse(fs.readFileSync(path.join(__dirname, "../examples/agency-decision/plan.json"), "utf8"));
const first = replayAgency(plan);
const second = replayAgency(plan);
assert.deepEqual(first, second, "replay preserves identical decision and execution history");
assert.equal(first.objective_reality["door.open"], false, "conflicting proposals resolve by stable identifier");
assert.equal(first.objective_reality["access.granted"], false, "forming goals never changes reality");
assert.deepEqual(first.agents["agent-a"].goals.map((goal) => goal.id), ["goal-exit"]);
assert.deepEqual(first.proposals, ["proposal-alpha-open", "proposal-bravo-close", "proposal-force-access", "proposal-route"], "proposal generation is deterministic");
const results = new Map(first.history.filter((item) => item.kind === "execution").map((item) => [item.id, item]));
assert.equal(results.get("proposal-force-access").status, "failed", "objective constraints reject proposals");
assert.equal(results.get("proposal-route").status, "interrupted", "interrupted plans remain historically visible");
assert.equal(results.get("proposal-alpha-open").status, "succeeded");
assert.ok(results.get("proposal-alpha-open").committed_event, "success changes reality only through committed execution");
assert.equal(first.agents["agent-a"].plans[0].status, "interrupted");
console.log("validated agency and decision model");
