const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { replay, stable, ORDERING_POLICY, reducerDefinitions } = require("../runtime/canonical-kernel.js");
const root = path.resolve(__dirname, "..");
const pack = JSON.parse(fs.readFileSync(path.join(root, "canon/reference-convergence/manifest.json"), "utf8"));
const events = JSON.parse(fs.readFileSync(path.join(root, "examples/reference-simulation/events.json"), "utf8"));
const fromZero = replay(events, pack);
const reordered = replay([...events].reverse(), pack);
const checkpoint = replay(events.slice(0, 6), pack);
const fromCheckpoint = replay(events, pack, { state: checkpoint.state });
assert.equal(ORDERING_POLICY, "time-phase-priority-sequence-id@v1");
assert.deepEqual(fromZero.projection, reordered.projection, "insertion order cannot change the objective projection");
assert.deepEqual(fromZero.projection, fromCheckpoint.projection, "checkpoint plus partial replay equals rebuild from zero");
assert.equal(fromZero.projection.objective.environment.connections["door-a-b"].locked, false);
assert.equal(fromZero.projection.objective.resources.key.custodian, "agent-b");
assert.equal(fromZero.state.local.beliefs["agent-a"].length, 1, "belief stays outside objective projection");
assert.equal(JSON.stringify(fromZero.projection).includes("beliefs"), false, "objective projection excludes observer-local state");
assert.equal(stable(fromZero.projection), stable(reordered.projection), "canonical serialization is stable");
assert.ok(reducerDefinitions.every((reducer) => reducer.domain && reducer.reads && reducer.writes));
assert.throws(() => replay([...events, { ...events[0] }], pack), /duplicate_event/);
assert.throws(() => replay([{ ...events[0], causal_parents: ["missing"] }], pack), /invalid_causal_parent/);
assert.throws(() => replay([{ ...events[0], id: "bad", type: "planning.plan.recorded", domain: "environment", causal_parents: [] }], pack), /illegal_domain_ownership/);
assert.throws(() => replay([{ ...events[0], id: "bad-contract", at: -1, causal_parents: [] }], pack), /invalid_event_contract/);
console.log("validated canonical event lifecycle, projection, ownership, and replay");
