const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { replay, stable, evaluateDecision } = require("../runtime/canonical-kernel.js");

const root = path.resolve(__dirname, "..");
const pack = JSON.parse(fs.readFileSync(path.join(root, "canon/reference-convergence/manifest.json"), "utf8"));
const baseEvents = JSON.parse(fs.readFileSync(path.join(root, "examples/reference-simulation/events.json"), "utf8"));
const base = replay(baseEvents, pack);
const perception = { id: "e12", session_id: "reference-session", sequence: 12, type: "perception.observation.recorded", version: "v1", at: 10, phase: "information", priority: 0, domain: "perception", world: { id: pack.id, version: pack.version }, causal_parents: ["e1"], payload: { observer: "agent-a", causal_source: "e1", result: { request_id: "observe-fire", observer: "agent-a", projection_identity: base.projection.identity, status: "observed", modality: "visual", target: "fire-glow", content: "fire glow", fidelity: 0.8, source: "e1" } } };
const knowledge = { id: "e13", session_id: "reference-session", sequence: 13, type: "epistemic.knowledge.acquired", version: "v1", at: 10, phase: "information", priority: 0, domain: "epistemic", world: { id: pack.id, version: pack.version }, causal_parents: ["e12"], payload: { id: "knowledge-fire", observer: "agent-a", proposition: "fire glow", basis: "perception", acquired_at: 10, provenance: { source_id: "e12", source_event: "e12", reliability: 0.8 } } };
const misleadingBelief = { id: "e14", session_id: "reference-session", sequence: 14, type: "epistemic.belief.formed", version: "v1", at: 10, phase: "information", priority: 0, domain: "epistemic", world: { id: pack.id, version: pack.version }, causal_parents: ["e2"], payload: { id: "belief-door-open", observer: "agent-a", proposition: "door-a-b is unlocked", confidence: 0.7, recorded_at: 10, provenance: { kind: "communication", id: "e2" } } };
const correction = { id: "e15", session_id: "reference-session", sequence: 15, type: "epistemic.knowledge.acquired", version: "v1", at: 10, phase: "information", priority: 0, domain: "epistemic", world: { id: pack.id, version: pack.version }, causal_parents: ["e6"], payload: { id: "knowledge-door-locked", observer: "agent-a", proposition: "door-a-b remained locked", basis: "validated_evidence", acquired_at: 10, provenance: { source_id: "e6", source_event: "e6", reliability: 1 } } };
const revisedBelief = { id: "e16", session_id: "reference-session", sequence: 16, type: "epistemic.belief.revised", version: "v1", at: 10, phase: "information", priority: 0, domain: "epistemic", world: { id: pack.id, version: pack.version }, causal_parents: ["e15"], payload: { id: "belief-door-locked", observer: "agent-a", proposition: "door-a-b remained locked", confidence: 1, recorded_at: 10, supersedes: "belief-door-open", provenance: { kind: "knowledge", id: "knowledge-door-locked" } } };
const conflictingBelief = { id: "e17", session_id: "reference-session", sequence: 17, type: "epistemic.belief.formed", version: "v1", at: 10, phase: "information", priority: 0, domain: "epistemic", world: { id: pack.id, version: pack.version }, causal_parents: ["e2"], payload: { id: "belief-door-open-b", observer: "agent-b", proposition: "door-a-b is unlocked", confidence: 0.9, recorded_at: 10, provenance: { kind: "communication", id: "e2" } } };
const epistemicEvents = [perception, knowledge, misleadingBelief, correction, revisedBelief, conflictingBelief];
const integrated = replay([...baseEvents, ...epistemicEvents], pack);
const reordered = replay([...epistemicEvents, ...[...baseEvents].reverse()], pack);
const request = { observer: "agent-a", projection_identity: integrated.projection.identity, goals: [{ id: "open-door", intent: "open-door", priority: 1, requires_proposition: "door-a-b is unlocked" }, { id: "inspect-fire", intent: "inspect-fire", priority: 2, requires_proposition: "fire glow" }], plans: [{ id: "exit-plan" }] };
const local = { perceptions: integrated.state.local.perceptions["agent-a"], knowledge: integrated.state.local.knowledge["agent-a"], beliefs: integrated.state.local.beliefs["agent-a"] };
const inputBefore = stable({ projection: integrated.projection, request, local });
const decision = evaluateDecision(integrated.projection, request, local);
const proposalEvent = { id: "e18", session_id: "reference-session", sequence: 18, type: "agency.action.proposed", version: "v1", at: 11, phase: "action", priority: 0, domain: "agency", world: { id: pack.id, version: pack.version }, causal_parents: ["e16"], payload: decision.proposals[0] };
const committed = replay([...baseEvents, ...epistemicEvents, proposalEvent], pack);

assert.equal(integrated.state.local.knowledge["agent-a"].length, 2, "valid perception and evidence paths acquire immutable knowledge");
assert.equal(integrated.state.local.knowledge["agent-b"], undefined, "knowledge never leaks between observers");
assert.ok(integrated.state.local.beliefs["agent-a"].some((belief) => belief.id === "belief-door-open") && integrated.state.local.beliefs["agent-a"].some((belief) => belief.id === "belief-door-locked"), "belief revision preserves the earlier belief");
assert.equal(integrated.state.local.beliefs["agent-b"][0].proposition, "door-a-b is unlocked", "observers may retain conflicting beliefs");
assert.equal(JSON.stringify(integrated.projection).includes("knowledge-fire"), false, "observer-local epistemic state excludes objective projection");
assert.equal(stable({ projection: integrated.projection, request, local }), inputBefore, "decision evaluation is pure");
assert.equal(decision.proposals[0].intent, "inspect-fire", "decisions consume local information without resolving objective truth");
assert.deepEqual(decision, evaluateDecision(reordered.projection, { ...request, projection_identity: reordered.projection.identity }, { perceptions: reordered.state.local.perceptions["agent-a"], knowledge: reordered.state.local.knowledge["agent-a"], beliefs: reordered.state.local.beliefs["agent-a"] }), "decision output is insertion-order independent");
assert.equal(committed.projection.objective.actions.at(-1).intent, "inspect-fire", "proposals become durable only through committed agency events");
assert.deepEqual(committed.projection, replay([...baseEvents, ...epistemicEvents, proposalEvent], pack).projection, "replay preserves epistemic and proposal history");
assert.throws(() => replay([...baseEvents, { ...knowledge, id: "bad-knowledge", causal_parents: [] }], pack), /invalid_knowledge_provenance/);
assert.throws(() => replay([...baseEvents, { ...revisedBelief, id: "bad-revision", causal_parents: ["e2"], payload: { ...revisedBelief.payload, supersedes: "missing" } }], pack), /invalid_belief_revision/);
assert.equal(evaluateDecision(integrated.projection, { ...request, projection_identity: "wrong" }, local).rejection, "projection_mismatch");
console.log("validated epistemic acquisition, belief revision, and deterministic decision proposals");
