const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { stable } = require("../runtime/canonical-kernel.js");
const { createSession, advanceSession, inspectSession, exportSession, restoreSession } = require("../runtime/session-api.js");

const root = path.resolve(__dirname, "..");
const pack = JSON.parse(fs.readFileSync(path.join(root, "canon/reference-convergence/manifest.json"), "utf8"));
const scenario = { id: "public-reference", world: { id: pack.id, version: pack.version }, initial_objective_overrides: { environment: { hazards: { "fire-b": { active: true } } } }, observers: [{ id: "agent-a", goals: [], plans: [] }, { id: "agent-b", goals: [], plans: [] }] };
const creation = { world_pack: pack, scenario, seed_material: { scenario_seed: "reference" } };
const first = createSession(creation), second = createSession({ seed_material: { scenario_seed: "reference" }, scenario: structuredClone(scenario), world_pack: structuredClone(pack) });
const activeTick = { id: "session-tick-1", at: 1, observers: [{ id: "agent-b", goals: [{ id: "b-fire", intent: "extinguish-fire", priority: 1 }], plans: [] }, { id: "agent-a", goals: [{ id: "a-fire", intent: "extinguish-fire", priority: 0 }], plans: [] }] };
const advanced = advanceSession({ session: first.session, tick: activeTick });
const exported = exportSession(advanced.session);
const restored = restoreSession(exported.envelope);
const idleTick = { id: "session-tick-2", at: 2, observers: [{ id: "agent-a", goals: [], plans: [] }, { id: "agent-b", goals: [], plans: [] }] };
const originalIdle = advanceSession({ session: advanced.session, tick: idleTick });
const restoredIdle = advanceSession({ session: restored.session, tick: idleTick });
const corrupt = structuredClone(exported.envelope); corrupt.session.history.push({ id: "bad" });
const mismatch = structuredClone(exported.envelope); mismatch.cache.projection_identity = "wrong";
const incompatible = structuredClone(pack); incompatible.kernel_compatibility = "other-kernel@v1";

assert.ok(first.ok && second.ok);
assert.equal(first.session.id, second.session.id, "session identity derives only from durable inputs");
assert.equal(stable(first.session), stable(second.session), "input object order cannot affect session output");
assert.ok(advanced.ok && advanced.events.length > 0, "session advancement delegates to the Director");
assert.equal(advanced.projection.objective.environment.hazards["fire-b"].active, false);
assert.ok(exported.ok && restored.ok, "export restores through canonical history");
assert.equal(restored.session.projection.identity, advanced.session.projection.identity);
assert.deepEqual(originalIdle.session.projection, restoredIdle.session.projection, "restored continuation is equivalent");
assert.equal(originalIdle.complete, true, "idle advancement reports session completion");
assert.equal(advanceSession({ session: originalIdle.session, tick: idleTick }).error.code, "SESSION_COMPLETE");
assert.equal(restoreSession(corrupt).error.code, "CORRUPTED_HISTORY");
assert.equal(restoreSession(mismatch).error.code, "PROJECTION_IDENTITY_MISMATCH");
assert.equal(createSession({ world_pack: incompatible, scenario }).error.code, "INCOMPATIBLE_KERNEL_VERSION");
assert.equal(createSession({ world_pack: pack, scenario: { ...scenario, world: { id: "wrong", version: "1" } } }).error.code, "INVALID_SCENARIO");
const startup = { profile: { id: "neutral-operator" }, player: { observer_id: "agent-a", role: "operator" }, knowledge: [{ observer_id: "agent-a", kind: "instruction", reference: "briefing-a" }], permissions: [{ observer_id: "agent-a", permission: "observe" }], resources: [{ id: "starter-kit", custodian: "agent-a", quantity: 1 }] };
const bootstrapped = createSession({ world_pack: pack, scenario, seed_material: { scenario_seed: "bootstrap" }, startup });
const bootstrappedAgain = createSession({ world_pack: structuredClone(pack), scenario: structuredClone(scenario), seed_material: { scenario_seed: "bootstrap" }, startup: structuredClone(startup) });
assert.ok(bootstrapped.ok && bootstrappedAgain.ok, "a declarative startup creates a public session");
assert.equal(stable(bootstrapped.session), stable(bootstrappedAgain.session), "startup is deterministic");
assert.equal(bootstrapped.session.history[0].type, "session.started", "startup is canonical history");
assert.deepEqual(bootstrapped.session.startup.knowledge, startup.knowledge, "knowledge remains startup-local");
assert.deepEqual(restoreSession(exportSession(bootstrapped.session).envelope).session.startup, bootstrapped.session.startup, "startup survives export and restore");
assert.equal(createSession({ world_pack: pack, scenario, startup: { ...startup, player: { observer_id: "missing" } } }).error.code, "INVALID_SESSION");
const copied = inspectSession(first.session); copied.session.projection.objective.environment.hazards["fire-b"].active = true;
assert.equal(inspectSession(first.session).session.projection.objective.environment.hazards["fire-b"].active, true, "public snapshots are defensive copies");
console.log("validated public sessions, adapter compatibility, persistence, and restoration");
